<link rel="stylesheet" href="/plugins/lora/easytext/src/css/easytext_core.css">
<link rel="stylesheet" href="/resources/plugins/easytext/blockstyles/easytext_styles.css">
<link rel="stylesheet" href="/public/css/plugins/custom_easytext.css">

<script src="/plugins/lora/easytext/src/js/loadDialog.js"></script>
<script src="/plugins/lora/easytext/src/js/colorTextCode.js"></script>
<script src="/plugins/lora/easytext/src/js/easyText.js"></script>
<script src="/plugins/lora/easytext/src/js/replaceText.js"></script>
<script src="/plugins/lora/easytext/src/js/editor.js"></script>
<script src="/plugins/lora/easytext/src/js/liveEditor.js"></script>