#!/usr/bin/php -q
<?php
    require ("App/Core/Autoload/Autoload.php");
    
    $autoload = new Autoload();
    $autoload->loadClass();
    
    $lora = new \Lora\Lora\Lora();
    $implode_cmds = implode(" ", $argv);
    $lora->prepareCommand($implode_cmds);
    //$loran->sendCommand(@htmlentities($argv[1]), @htmlentities($argv[2]), @htmlentities($argv[3]), @htmlentities($argv[4]));
?>
