#!/usr/bin/php -q
<?php
    error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);

    require ("App/Core/Autoload/Autoload.php");
    
    $autoload = new Autoload();
    $autoload->loadClass();
    
    $lora = new \Lora\Lora\Lora();
    $implode_cmds = implode(" ", $argv);
    $lora->prepareCommand($implode_cmds);
?>
