<!-- HTML Loader for plugin 'eText'. Load this page at index.lo.php at ./resources/views using directivy: @pluginhtml lora/eText @ -->
<link rel="stylesheet" href="/plugins/lora/etext/src/css/etext.css">
<link rel="stylesheet" href="/plugins/lora/etext/src/css/init.css">

<script src="/plugins/lora/etext/src/js/buttons.js"></script>
<script src="/plugins/lora/etext/src/js/liveEditor.js"></script>
<script src="/plugins/lora/etext/src/js/app.js"></script>