<!DOCTYPE html>
<html>
    <head>
        <style>
            {style}
            {style-custom}
        </style>
        <meta charset="utf-8">
    </head>

    <body class="background-dark-3">
        <div>
            <header class="pd-3 background-dark header-6 content-center">
                <div class="">
                    <img class="height-128p" src="{logo-src}" alt="Company logo">
                </div>
                <div class="header-4 t-bold t-custom-2">{company-name}</div>
            </header>

            <main class="pd-1">
                <div class="subject">
                    <span class="t-custom-1">Předmět:</span> {subject}
                </div>
                <span class="t-custom-1">Zpráva od:</span> <span style="font-weight: bolder">{from}</span> <br>
                <hr>
                <div class="header-6 pd-1">
                    {message}
                </div>
            </main>

            <footer class="background-dark pd-2">
                Tento email byl zaslán prostřednictvím systému Mailer by DXGamePRO. Pokud jste na webu <span class="t-custom-2">{Web_url}</span> nic neučinili anebo web nenavšítvili, prosíme, nereagujte na něj.
            </footer>
        </div>
    </body>
</html>
