<div style="margin-bottom: 1em;">Vážený/á uživateli/uživatelko <b>{email_full}</b>!
Na základě Vaší žádosti Vám zasíláme formulář pro obnovu hesla do webové aplikace {web_name}.</div>

<div style="text-align: center; ">
Pokračujte dále stisknutím tlačítka: <br><br>
<a href="{web_url}/auth/request-recover-password/{recover_code}/{email}" class="button button-create" style="text-underline: none;">Obnovit heslo</a>
</div>