<div style="font-size: 3rem; text-align: center; margin-bottom: .5em;">Vítejte na webu {web_name}!</div>
<div style="margin-bottom: 1em;">Děkujeme uživateli/uživatelko <b>{new_user}</b> za registraci na našem webu <b>{web_name}</b>!
Jsme opravdu moc rádi, že se k nám připojíte a doufáme, že se u nás budete cítit jako doma.</div>

<div style="text-align: center; ">
Jako další krok je nutné ověřit Vaší emailovou adresu, kterou jste zadal/a při registraci. 
Kliknutím na odkaz níže aktivujete svůj účet: <br><br>
<a href="{web_url}/auth/verify/{verify_code}/{email}" class="button button-create" style="text-underline: none;">Ověřit účet</a>
</div>