<div style="margin-bottom: 1em;">Vážený/á uživateli/uživatelko <b>{user}</b>!
Oznamujeme Vám, že Váš učet na webu {web_name} byl nenávratně smazán.</div>

<div style="margin-bottom: 1em;">
    <b>Proč byl můj účet smazán?</b>
    <ul>
        <li>Na Vašem účtu jsme dlouhodobě nezaznamenali žádnou aktivitu (viz. pravidla registrace)</li>
        <li>Váš účet nesplňuje podmínky na webu (viz. pravidla registrace)</li>
        <li>Váš účet vykazoval atypické chování a z důvodu bezpečnosti byl smazán</li>
        <li>O smazání Vašeho účtu jste požádal/a vy sám/a</li>
        <li>Jiný důvod, který jsme Vám zaslali dalším emailem</li>
    </ul>
</div>