<div class="header-5 content-center">
    Dostal/a jste odpověď k Vašemu komentáři k produktu <span class="t-custom-2 t-bold">{product-name}</span>
</div>

<div class="header-6 t-italic pdy-2">   
    Vážený zákazníku,<br>
    Byla Vám zodpovězena otázka, kterou jste položil/a na našem eshopu {company-name}<br><br>
    Klikněte <a href="{host}/mshop/shop/product-show/{product-code}#disscussion-{disscussion-id}" class="button button-custom-main-1">ZDE</a> pro zobrazení
    
</div>