<div class="header-5 content-center">
    Smutně Vám hlásíme, že objednávka č. <span class="t-custom-2 t-bold">{order-id}</span> byla zrušena
</div>

<div class="header-6 t-italic pdy-2">   
    Na Vaší žádost nebo kvůli technickým problémům byla Vaše objednávka ze dne: {date} bohužel zrušena. Pro více informací nás neváhejte kontaktovat na našem emailu: <span class="t-custom-2 t-bold">{email}</span>
    nebo tel. čísle <span class="t-custom-2 t-bold">{phone}</span>
</div>

<div class="t-bold">
    Doufáme, že příští objednávka se Vám povede a my Vám budeme moci udělat naším zbožím radost.
</div>



