<div class="header-5 content-center">
    Vámi zvolený způsob úhrady je: <span class="t-custom-2">Platba při převzetí</span>
</div>
<div class="t-bold">
    Co to pro Vás znamená?
</div>

<div class="header-6 t-italic pdy-2">
    Naše firma má smluvenou přepravu zboží pomocí České pošty, a již nyní Vám zboží balíme a co nejdříve jej předáme dopravci.
    Dopravce Vás bude pomocí trasování zásilky informovat, kdy zboží dostanete. Jakmile zboží budete přebírat, zaplatíte dopravci částku: <span class="t-custom-2 t-bolder">{_suma} Kč</span>
        ({suma} + {delivery-cost}) Kč</b>. Zkontrolujte si prosím přebíranou zásilku! Pokud je poškozená, nepřebírejte jí.
</div>