<div class="header-5 content-center">
    Vaše zboží je již na cestě!
</div>

<div class="header-6 t-italic pdy-2">   
    Neseme Vám dobré zprávy! Zboží, které jste dne {date} objednal je již na cestě k Vám. Pokud Vámi zvolená forma úhrady je <b>vyzvednutí na pobočce</b>, tak hlásíme, 
    že zboží je v tuto chvíli připraveno k odběru! Prosím, pozorně si přečtěte pokyny k jednotlivým platbám, ať přejdeme nesrovnalostem.
</div>

<div class="t-bold">
    Moc Vám děkujeme za Váš nákup a doufáme, že si zboží od nás co nejvíce užijete!
</div>


