<div class="pdy-2 header-3 content-center">
    Děkujeme Vám za nákup zboží v našem eshopu {company-name}!
</div>

<div class="header-6 t-custom-1 content-center">
    Doufáme, že Vám produkty zakoupené u nás budou dělat radost a vydrží navěky ;)
</div>

<div class="t-bold">
    Informace o stavu Vaší objednávky č. {order-id}
</div>

<div class="t-italic pdy-2">
    Vyčkejte prosím na zpracování objednávky, obratem obdržíte informaci k Vámi vybrané formě úhrady
</div>

<hr>

<div class="header-3 pdy-1 t-bold">Příloha: FAKTURA</div>

<div class="pd-2">
    {invoice}
</div>