<div class="pdy-2 header-3 content-center">
    Děkujeme Vám za nákup zboží v našem eshopu {company-name}!
</div>

<div class="header-6 t-custom-1 content-center">
    Doufáme, že Vám produkty zakoupené u nás budou dělat radost a vydrží navěky ;)
</div>

<div class="t-bold">
    Informace o stavu Vaší objednávky č. {order-id}
</div>

<div class="mgy-3 row pd-1 pdy-1 background-dark t-bolder subheader-3">
    <div class="column-1">Počet</div>
    <div class="column-2">Popis</div>
    <div class="column-1 content-center">Cena</div>
    <div class="column-1 content-center">Sazba DPH</div>
    <div class="column-2 content-center">Zákl. DPH</div>
    <div class="column-1 content-center">DPH</div>
    <div class="column content-center">Celkem</div>
</div>
<hr>
<div class="pdy-1">
    {products-table}
</div>

<div class="content-center header-5 pdy-3">
    Celková částka k zaplacení: {suma} Kč + {delivery-cost} Kč poštovné = <span class='t-custom-2'>{-suma} Kč</span>
</div>