<div class="header-5 content-center">
    Vámi zvolený způsob úhrady je: <span class="t-custom-2">Platba předem</span>
</div>
<div class="t-bold">
    Co to pro Vás znamená?
</div>

<div class="header-6 t-italic pdy-2">
    Abychom dokončili Vaší objednávku, je nutné od Vás obdržet částku ve výši: <span class="t-custom-2 t-bolder">{_suma} Kč</span>
    ({suma} + {delivery-cost}) Kč</b> na bankovní účet č.: <span class="t-custom-2 t-bolder">XXXXXXX/0100</span>, 
    variabilní symbol: <span class="t-custom-2 t-bolder">{order-id}</span>, konstantní symbol: <span class="t-custom-2 t-bolder">{id}</span>.<br>
    
    Jakmile Vaší platbu obdržíme, zboží ihned zašleme na Vaší adresu: <span class="t-custom-2 t-bolder">{address}</span>
    
</div>
