<div class="header-5 content-center">
    Vámi zvolený způsob úhrady je: <span class="t-custom-2">Vyzvednutí na pobočce</span>
</div>

<div class="t-bold">
    Co to pro Vás znamená?
</div>

<div class="header-6 t-italic pdy-2">   
    Až Vám zašleme, že zboží je připraveno k odběru, dostavte se v úřední hodiny na Vámi vybranou pobočku: <span class="t-custom-2">{branch}</span> a vyzvedněte si zde zboží v hodnotě <span class="t-custom-2">{suma} Kč</span>. 
    Lze platit i kartou. Na pobočce sdělte Váš symbol: <span class="t-custom-2">{order-id}</span> a my po Vašem zaplacení na prodejně zboží vydáme.
</div>

